rm -rf Classes/*~
rm -rf client/*~
rm -rf cmd/*~
rm -rf ctrl/*~
rm -rf doc/*~
rm -rf game/*~
rm -rf game/robot/*~
rm -rf game/robot/cmd/*~
rm -rf game/proper/*~
rm -rf game/time/*~
rm -rf gui/*~
rm -rf log/*~
rm -rf ogl/*~
rm -rf server/*~
rm -rf tst/*~
rm -rf ctrl/*~
rm -rf ctrl/manual/*~
rm -rf ctrl/programmed/*~
